# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Hydroflow
                                 A QGIS plugin
 Compute drainage orders in drainage basins using Strahler and Shreve methods
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-07
        copyright            : (C) 2024 by Henrique Uzêda
        email                : hruzeda@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):  # pylint: disable=invalid-name  NOSONAR
    """Load Hydroflow class from file Hydroflow.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hydroflow import Hydroflow

    return Hydroflow(iface)
