# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmlog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmLog(object):
    def setupUi(self, FrmLog: QtWidgets.QDialog) -> None:
        FrmLog.setObjectName("FrmLog")
        FrmLog.setWindowModality(QtCore.Qt.ApplicationModal)
        FrmLog.resize(521, 353)
        FrmLog.setMinimumSize(QtCore.QSize(521, 353))
        FrmLog.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":hydroflow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        FrmLog.setWindowIcon(icon)
        FrmLog.setSizeGripEnabled(False)
        self.pushButton = QtWidgets.QPushButton(FrmLog)
        self.pushButton.setGeometry(QtCore.QRect(344, 309, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(FrmLog)
        self.pushButton_2.setGeometry(QtCore.QRect(435, 309, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(FrmLog)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 501, 285))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(FrmLog)
        QtCore.QMetaObject.connectSlotsByName(FrmLog)

    def retranslateUi(self, FrmLog: QtWidgets.QDialog) -> None:
        _translate = QtCore.QCoreApplication.translate
        FrmLog.setWindowTitle(_translate("FrmLog", "Log de processamento"))
        self.pushButton.setText(_translate("FrmLog", "Salvar"))
        self.pushButton_2.setText(_translate("FrmLog", "Fechar"))


from . import resources_rc  # noqa: F401, E402
