# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\henrique\Desktop\hydroflow\hydroflow-python-plugin\hydroflow_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HydroflowDialogBase(object):
    def __init__(self):
        self.pushButton_Close = QtWidgets.QPushButton(self)
        self.pushButton_Exec: QtWidgets.QPushButton
        self.groupBox_Lim: QtWidgets.QGroupBox
        self.lineEdit_Lim: QtWidgets.QLineEdit
        self.pushButton_Lim: QtWidgets.QPushButton
        self.groupBox: QtWidgets.QGroupBox
        self.label: QtWidgets.QLabel
        self.comboBox: QtWidgets.QComboBox
        self.label_2: QtWidgets.QLabel
        self.lineEdit_TolXY: QtWidgets.QLineEdit
        self.label_3: QtWidgets.QLabel
        self.checkBox_Strahler: QtWidgets.QCheckBox
        self.checkBox_Shreve: QtWidgets.QCheckBox
        self.checkBox_FlowOnly: QtWidgets.QCheckBox
        self.groupBox_HidLn: QtWidgets.QGroupBox
        self.lineEdit_HidLn: QtWidgets.QLineEdit
        self.pushButton_HidLn: QtWidgets.QPushButton

    def setupUi(self, HydroflowDialogBase):
        HydroflowDialogBase.setObjectName("HydroflowDialogBase")
        HydroflowDialogBase.resize(464, 276)
        self.pushButton_Close = QtWidgets.QPushButton(HydroflowDialogBase)
        self.pushButton_Close.setGeometry(QtCore.QRect(347, 220, 88, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_Close.setFont(font)
        self.pushButton_Close.setFlat(False)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.pushButton_Exec = QtWidgets.QPushButton(HydroflowDialogBase)
        self.pushButton_Exec.setEnabled(False)
        self.pushButton_Exec.setGeometry(QtCore.QRect(347, 162, 88, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_Exec.setFont(font)
        self.pushButton_Exec.setObjectName("pushButton_Exec")
        self.groupBox_Lim = QtWidgets.QGroupBox(HydroflowDialogBase)
        self.groupBox_Lim.setGeometry(QtCore.QRect(10, 82, 441, 61))
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_Lim.setFont(font)
        self.groupBox_Lim.setObjectName("groupBox_Lim")
        self.lineEdit_Lim = QtWidgets.QLineEdit(self.groupBox_Lim)
        self.lineEdit_Lim.setEnabled(False)
        self.lineEdit_Lim.setGeometry(QtCore.QRect(6, 28, 381, 28))
        self.lineEdit_Lim.setObjectName("lineEdit_Lim")
        self.pushButton_Lim = QtWidgets.QPushButton(self.groupBox_Lim)
        self.pushButton_Lim.setGeometry(QtCore.QRect(400, 28, 30, 28))
        self.pushButton_Lim.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Lim.setIcon(icon)
        self.pushButton_Lim.setObjectName("pushButton_Lim")
        self.groupBox = QtWidgets.QGroupBox(HydroflowDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(10, 142, 314, 122))
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 105, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_TolXY = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_TolXY.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_TolXY.setText("0.001")
        self.lineEdit_TolXY.setObjectName("lineEdit_TolXY")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(145, 20, 51, 16))
        self.label_3.setObjectName("label_3")
        self.checkBox_Strahler = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Strahler.setGeometry(QtCore.QRect(145, 40, 131, 18))
        self.checkBox_Strahler.setChecked(True)
        self.checkBox_Strahler.setObjectName("checkBox_Strahler")
        self.checkBox_Shreve = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Shreve.setGeometry(QtCore.QRect(145, 65, 131, 18))
        self.checkBox_Shreve.setChecked(True)
        self.checkBox_Shreve.setObjectName("checkBox_Shreve")
        self.checkBox_FlowOnly = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_FlowOnly.setGeometry(QtCore.QRect(145, 91, 131, 18))
        self.checkBox_FlowOnly.setObjectName("checkBox_FlowOnly")
        self.groupBox_HidLn = QtWidgets.QGroupBox(HydroflowDialogBase)
        self.groupBox_HidLn.setGeometry(QtCore.QRect(10, 10, 441, 61))
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_HidLn.setFont(font)
        self.groupBox_HidLn.setObjectName("groupBox_HidLn")
        self.lineEdit_HidLn = QtWidgets.QLineEdit(self.groupBox_HidLn)
        self.lineEdit_HidLn.setEnabled(False)
        self.lineEdit_HidLn.setGeometry(QtCore.QRect(5, 28, 381, 28))
        self.lineEdit_HidLn.setObjectName("lineEdit_HidLn")
        self.pushButton_HidLn = QtWidgets.QPushButton(self.groupBox_HidLn)
        self.pushButton_HidLn.setGeometry(QtCore.QRect(400, 28, 30, 28))
        self.pushButton_HidLn.setText("")
        self.pushButton_HidLn.setIcon(icon)
        self.pushButton_HidLn.setObjectName("pushButton_HidLn")

        self.retranslateUi(HydroflowDialogBase)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HydroflowDialogBase)

    def retranslateUi(self, HydroflowDialogBase):
        _translate = QtCore.QCoreApplication.translate
        HydroflowDialogBase.setWindowTitle(_translate("HydroflowDialogBase", "Hydroflow"))
        self.pushButton_Close.setText(_translate("HydroflowDialogBase", "Fechar"))
        self.pushButton_Exec.setText(_translate("HydroflowDialogBase", "Executar"))
        self.groupBox_Lim.setTitle(_translate("HydroflowDialogBase", " Limite da área "))
        self.groupBox.setTitle(_translate("HydroflowDialogBase", " Opções "))
        self.label.setText(_translate("HydroflowDialogBase", "Unidade do mapa:"))
        self.comboBox.setItemText(0, _translate("HydroflowDialogBase", "Metros"))
        self.comboBox.setItemText(1, _translate("HydroflowDialogBase", "Quilômetros"))
        self.comboBox.setItemText(2, _translate("HydroflowDialogBase", "Pés"))
        self.comboBox.setItemText(3, _translate("HydroflowDialogBase", "Outro"))
        self.label_2.setText(_translate("HydroflowDialogBase", "Tolerância XY:"))
        self.label_3.setText(_translate("HydroflowDialogBase", "Inferir:"))
        self.checkBox_Strahler.setText(_translate("HydroflowDialogBase", "Ordens por Strahler"))
        self.checkBox_Shreve.setText(_translate("HydroflowDialogBase", "Ordens por Shreve"))
        self.checkBox_FlowOnly.setText(_translate("HydroflowDialogBase", "Somente fluxos"))
        self.groupBox_HidLn.setTitle(_translate("HydroflowDialogBase", " Rede de drenagem "))

from . import resources_rc  # noqa: E402, F401
