[tool.ruff]
target-version = "py312"
line-length = 85

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

[tool.mypy]
python_version = "3.12"
explicit_package_bases = false
namespace_packages = false
strict = true
disallow_subclassing_any = false
disallow_untyped_decorators = false
exclude = [
  'frmlog_ui.py',
  'hydroflow_dialog_base_ui.py',
  'plugin_upload.py',
  'resources_rc.py',
  'test',
]

[[tool.mypy.overrides]]
module = ['qgis.*', 'PyQt6.*']
ignore_errors = true
ignore_missing_imports = true
