ioPaths:
  -
    - "hydroflow_dialog_base.ui"
    - "hydroflow_dialog_base_ui.py"
  -
    - "frmlog.ui"
    - "frmlog_ui.py"
  -
    - "resources.qrc"
    - "resources_rc.py"

uic_options: --from-imports
init_package: True
force: False